#!/usr/bin/env python3
"""
jarvis-rag-server - MCP server that exposes Mavis mavis-rag as MCP tool.
Auto-generated by mavis-mcp.
"""
import asyncio
import sys

# Minimal MCP stdio server using mcp library if available
try:
    from mcp.server import Server
    from mcp.server.stdio import stdio_server
    from mcp.types import TextContent, Tool
    HAS_MCP = True
except ImportError:
    HAS_MCP = False
    print("Warning: mcp library not installed. Install: pip install mcp", file=sys.stderr)


if HAS_MCP:
    server = Server("jarvis-rag-server")

    @server.list_tools()
    async def list_tools():
        return [Tool(
            name="mavis-rag",
            description="Mavis mavis-rag exposed as MCP tool",
            inputSchema={
                "type": "object",
                "properties": {
                    "prompt": {"type": "string", "description": "Input prompt"}
                },
                "required": ["prompt"]
            }
        )]

    @server.call_tool()
    async def call_tool(name: str, arguments: dict):
        # Delegate to /usr/local/bin/mavis-rag
        result = subprocess_run([name, arguments.get("prompt", "")])
        return [TextContent(type="text", text=result)]


def subprocess_run(cmd, *args):
    import subprocess
    return subprocess.run(cmd, capture_output=True, text=True).stdout


def main():
    if not HAS_MCP:
        print("Install mcp: pip install mcp", file=sys.stderr)
        sys.exit(1)
    asyncio.run(run_server())


async def run_server():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())


if __name__ == "__main__":
    main()
