#!/usr/bin/env python3
"""
mavis-mcp.py — MCP (Model Context Protocol) server creator for Mavis.

The top 1% agents (Claude Code, Cursor) have MCP server integration.
This script helps Mavis create MCP servers that expose Mavis tools
to other Claude Code / Cursor / Windsurf clients.

Usage:
  mavis-mcp list                              # list installed MCP servers
  mavis-mcp create --name myserver --tool mavis-rag
  mavis-mcp install-server /path/to/server.py # install as mavis MCP server
"""
import argparse
import json
import os
import sys
from pathlib import Path

# Default location for MCP config
MCP_CONFIG_PATHS = [
    Path("/root/.claude/mcp_servers.json"),
    Path("/root/.config/Claude/claude_desktop_config.json"),
    Path(os.path.expanduser("~/.cursor/mcp.json")),
]


def list_installed() -> list:
    """List installed MCP servers from all known config paths."""
    found = []
    for path in MCP_CONFIG_PATHS:
        if not path.exists():
            continue
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError:
            continue
        # Different formats per client
        servers = data.get("mcpServers", data)
        if isinstance(servers, dict):
            for name, config in servers.items():
                found.append({"client": path.parent.name or path.name, "name": name, "config": config, "path": str(path)})
    return found


def install_server(name: str, command: str, args: list, env: dict | None = None, client: str = "claude") -> str:
    """Install an MCP server to the given client's config."""
    if client == "claude":
        config_path = Path("/root/.claude/mcp_servers.json")
    elif client == "cursor":
        config_path = Path("/root/.cursor/mcp.json")
    elif client == "desktop":
        config_path = Path("/root/.config/Claude/claude_desktop_config.json")
    else:
        config_path = Path("/root/.claude/mcp_servers.json")
    config_path.parent.mkdir(parents=True, exist_ok=True)

    if config_path.exists():
        try:
            data = json.loads(config_path.read_text())
        except json.JSONDecodeError:
            data = {}
    else:
        data = {}

    if "mcpServers" not in data:
        data["mcpServers"] = {}

    data["mcpServers"][name] = {
        "command": command,
        "args": args,
    }
    if env:
        data["mcpServers"][name]["env"] = env

    config_path.write_text(json.dumps(data, indent=2))
    return str(config_path)


def create_server_template(name: str, tool_script: str) -> str:
    """Generate a minimal MCP server template that wraps a Mavis tool."""
    template = f'''#!/usr/bin/env python3
"""
{name} - MCP server that exposes Mavis {tool_script} as MCP tool.
Auto-generated by mavis-mcp.
"""
import sys
import os
import json
import asyncio
from pathlib import Path

# Minimal MCP stdio server using mcp library if available
try:
    from mcp.server import Server
    from mcp.server.stdio import stdio_server
    from mcp.types import Tool, TextContent
    HAS_MCP = True
except ImportError:
    HAS_MCP = False
    print("Warning: mcp library not installed. Install: pip install mcp", file=sys.stderr)


if HAS_MCP:
    server = Server("{name}")

    @server.list_tools()
    async def list_tools():
        return [Tool(
            name="{tool_script}",
            description="Mavis {tool_script} exposed as MCP tool",
            inputSchema={{
                "type": "object",
                "properties": {{
                    "prompt": {{"type": "string", "description": "Input prompt"}}
                }},
                "required": ["prompt"]
            }}
        )]

    @server.call_tool()
    async def call_tool(name: str, arguments: dict):
        # Delegate to /usr/local/bin/{tool_script}
        result = subprocess_run([name, arguments.get("prompt", "")])
        return [TextContent(type="text", text=result)]


def subprocess_run(cmd, *args):
    import subprocess
    return subprocess.run(cmd, capture_output=True, text=True).stdout


def main():
    if not HAS_MCP:
        print("Install mcp: pip install mcp", file=sys.stderr)
        sys.exit(1)
    asyncio.run(run_server())


async def run_server():
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, server.create_initialization_options())


if __name__ == "__main__":
    main()
'''
    return template


def main():
    p = argparse.ArgumentParser()
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="List installed MCP servers")

    p_create = sub.add_parser("create", help="Create MCP server template")
    p_create.add_argument("--name", required=True, help="Server name")
    p_create.add_argument("--tool", required=True, help="Mavis tool to wrap (e.g. mavis-rag)")
    p_create.add_argument("--output", help="Output file path (default: ./<name>_mcp_server.py)")

    p_install = sub.add_parser("install-server", help="Install MCP server config")
    p_install.add_argument("--name", required=True)
    p_install.add_argument("--command", required=True)
    p_install.add_argument("--args", nargs="+", default=[])
    p_install.add_argument("--client", default="claude", choices=["claude", "cursor", "desktop"])
    p_install.add_argument("--env", nargs="+", default=[], help="KEY=VALUE pairs")

    args = p.parse_args()

    if args.cmd == "list":
        servers = list_installed()
        if not servers:
            print("🤷 No MCP servers installed yet.")
            print("   Create one: mavis-mcp create --name myserver --tool mavis-rag")
            return 0
        print(f"📡 {len(servers)} MCP server(s) installed:")
        for s in servers:
            print(f"   - {s['name']} ({s['client']}) → {s['config'].get('command', '?')}")
        return 0

    elif args.cmd == "create":
        template = create_server_template(args.name, args.tool)
        out_path = args.output or f"/workspace/jarvis/scripts/{args.name}_mcp_server.py"
        Path(out_path).write_text(template)
        Path(out_path).chmod(0o755)
        print(f"✅ Created MCP server template at {out_path}")
        print(f"   Next: mavis-mcp install-server --name {args.name} --command python3 --args {out_path}")
        return 0

    elif args.cmd == "install-server":
        env_dict = {}
        for kv in args.env:
            k, v = kv.split("=", 1)
            env_dict[k] = v
        config_path = install_server(args.name, args.command, args.args, env_dict, args.client)
        print(f"✅ Installed '{args.name}' in {config_path}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
